---
  team_mappings:
    Engineering: 0
    QA: 20
    PM: 30
    Exec: 10
  specialty_mappings:
    web: 5
    qa: 0
    mobile: 1
    hybrid: 2
    exec: 3
    pm: 4
  weights:
    days_here: 0.1
    team: 0.7
    specialty: 0.2
  min_lunch_group_size: 3
  min_group_score: 0.0001
  time_decay_constant: 80.0
